### ISSUE TITLE
COMMAND No 9  - npm run hot

### ISSUE THREAD

**Issue by b1tw0rker** [sinan-aydogan/anemon-laravel#4]
YOUR COMMAND NR 9  - npm run hot

produces the following error on my console:

> mix watch --hot

sh: mix: command not found

Even: 

npm install laravel-mix@latest --save-dev

could not fix this issue.

**Comment by emredipi** [comment]
This seems not related to the project. Ensure that you are using a newer version of npm. Since the mix is already in the project dependencies you don't have to reinstall it.

After that, try these steps.

1) to remove all node packages run this command in the project folder
`rm -rf node_modules`

2) install npm dependencies
`npm install`

3) serve
`npm run serve`
